name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:

  ubuntu-gcc6:
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Install gcc-6
        run: |
          sudo apt-get update && \
          sudo apt-get install \
            build-essential software-properties-common -y && \
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
          sudo apt-get update && \
          sudo apt-get install gcc-6 g++-6 -y && \
          gcc -v

      - name: Run build
        env:
          CC: gcc-6
          CXX: g++-6
        run: |
          (cd ./consapp/convbin/gcc; ls -l; make clean all test);
          (cd ./consapp/str2str/gcc; ls -l; make clean all)
